export enum IconType {
    ADD = 'ADD',
    CHECKMARK = 'CHECKMARK',
    FAVOURITE_DEFAULT = 'FAVOURITE_DEFAULT',
    FAVOURITE_SELECTED = 'FAVOURITE_SELECTED',
    FILTER = 'FILTER',
    REMOVE = 'REMOVE',
}
