export enum ProposalActionType {
    WITHDRAW_TOKEN = 'WITHDRAW_TOKEN',
    TOKEN_MINT = 'TOKEN_MINT',
    UPDATE_SETTINGS_MULTISIG = 'UPDATE_SETTINGS_MULTISIG',
    UPDATE_SETTINGS_TOKENVOTE = 'UPDATE_SETTINGS_TOKENVOTE',
}
